name: 'Validate Configuration (JSON Schema)'
description: 'Valida el app/config.json contra un esquema estricto y exporta variables'
outputs:
  language:
    description: "Lenguaje validado"
    value: ${{ steps.export.outputs.language }}
  version:
    description: "Versión validada"
    value: ${{ steps.export.outputs.version }}
  security_level:
    description: "Nivel de seguridad"
    value: ${{ steps.export.outputs.security_level }}

runs:
  using: "composite"
  steps:
    # 1. Verificar existencia del archivo
    - name: Check file existence
      run: |
        if [ ! -f "app/config.json" ]; then
          echo "ERROR CRÍTICO: No se encuentra 'app/config.json' en la raíz."
          exit 1
        fi
      shell: bash

    # 2. Preparar entorno Node (rápido y necesario para AJV)
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. VALIDACIÓN FUERTE (El Gatekeeper)
    # ${{ github.action_path }} es la ruta donde está esta action en el runner
    - name: Validate JSON Schema
      env:
        NPM_CONFIG_LOGLEVEL: error
      run: |
        echo "Validando configuración contra el esquema corporativo..."
        
        # Instalamos el validador al vuelo (es muy ligero) y validamos
        npx -y ajv-cli validate -s ${{ github.action_path }}/schemas/config-schema.json -d app/config.json
        
        if [ $? -eq 0 ]; then
          echo "Configuración VÁLIDA. Cumple con los estándares."
        else
          echo "ERROR DE GOBERNANZA: El archivo app/config.json no cumple el esquema."
          exit 1
        fi
      shell: bash

    # 4. Exportar variables (Solo si pasó la validación anterior)
    - name: Export Config Variables
      id: export
      run: |
        # Usamos jq para extraer valores seguros
        LANG=$(jq -r .language app/config.json)
        VER=$(jq -r .version app/config.json)
        SEC=$(jq -r '.security_level // "medium"' app/config.json) # Default medium
        
        echo "language=$LANG" >> $GITHUB_OUTPUT
        echo "version=$VER" >> $GITHUB_OUTPUT
        echo "security_level=$SEC" >> $GITHUB_OUTPUT
        
        echo "Variables detectadas: Lang=$LANG, Ver=$VER, Sec=$SEC"
      shell: bash
